### ISSUE TITLE
Set up Generic Project Board

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#15]
Hi @rossfarrugia Did you you still want to have a generic board set up for users? 

@dinakar29 Is that something we can set up in a template repo?

**Comment by cicdguy** [comment]
Hi @bms63,

There are 2 types of projects on Github. One is the Classic versions, and then there's the new, improved Projects in Beta.

Neither of them support custom templates, unfortunately. They both come with pre-defined templates that look like this:

> Classic

<img width="458" alt="Screen Shot 2022-06-21 at 10 25 49 AM" src="https://user-images.githubusercontent.com/26552821/174837932-2238acbe-b639-4551-bbfe-e4fdc42c0fef.png">

> New (in Beta)
<img width="597" alt="Screen Shot 2022-06-21 at 10 26 52 AM" src="https://user-images.githubusercontent.com/26552821/174838544-74961629-692c-4067-a7b0-a2d4a5caf8d3.png">

So defining these in the template repo wouldn't make a difference.

However, organization level projects can be created, which can be shared amongst multiple repositories. See here for org-level projects: https://github.com/orgs/pharmaverse/projects

**Comment by bms63** [comment]
Ohhh I like that organization level projects can be created.  Maybe the person who is scrum master for the optha could make this for us?  @rossfarrugia

**Comment by rossfarrugia** [comment]
hmm... what do you think @jj1994 or @duniek? 

i think it might end up a cluttered list as i imagine we'll have lots of these by the end. my vote would be to just add in the README that they need to set up their own repo project board and we can point to one of ours as an example.

**Comment by rossfarrugia** [comment]
Actually we already have this in the README:
`Set up a project board, such as [link](https://github.com/pharmaverse/admiral/projects/1), to help manage your backlog.`

I'll close this unless anyone disagrees and feel free to re-open.

**Comment by jj1994** [comment]
Hi @rossfarrugia & @bms63,

I think it is as @rossfarrugia mentions, too much clutter and it will not be easy to have an overview of all the ongoing issues. The way we would have it now is easier and I would not want to confuse the developers. Especially when some of them are not having any prior experience with Scrum or what it means to work in an agile way of working. I would maybe recommend this to a team that is a bit more established.
