### ISSUE TITLE
Set up Branch Protection Rules

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#16]
We mention a need for branch protection rules.  @rossfarrugia @dinakar29 is this something we still want and can we set it up?

**Comment by bms63** [comment]
![image](https://user-images.githubusercontent.com/10111024/174837694-6bf43a1e-fef5-4525-8da8-24aad1569f54.png)

**Comment by cicdguy** [comment]
Branch protection rules do not get copied to repositories that are based on templates, unfortunately 😢 
So if you define BPRs in `admiraltemplate`, they only apply to `admiraltemplate` and not repositories that are based on the template.

**Comment by bms63** [comment]
Okay.  good to know.  Maybe we should have a short recommendation blurb on protecting `main/devel` and being careful with who gets admin and write rights?

**Comment by cicdguy** [comment]
Yes, good idea on having documentation for that. That would be the best way to do it.

**Comment by bms63** [comment]
Okay I made a note and put a link in the readme around branch protection rules.
