### ISSUE TITLE
Bring over all badges (RMD-Check, codecov, etc)

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#2]

**Comment by bms63** [comment]
@rossfarrugia  I brought the code that makes the badges.  Do we want to have generic stand-ins?  Right now we just use the admiral badges.

**Comment by rossfarrugia** [comment]
fine to have them as you have it but you'd need to add a note to the to-do list at the bottom of the readme to ensure these get updated to their own repos.
