### ISSUE TITLE
Documentation:  Add README.md to workflows folder

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraltemplate#21]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

`README.md` should be added to the `workflows` folder. For each workflow in the `workflows` folder it should provide:
- A short description of the workflow.
- Prerequisites for using the workflow.

**Comment by cicdguy** [comment]
Also we need a section on creating orphan branches for the `badges`

**Comment by bundfussr** [comment]
@dinakar29 , isn't this a prerequisite for the code-coverage workflow? Or is it a more general requirement?

**Comment by cicdguy** [comment]
It is a prerequisite for the code coverage workflow.  Where does it make sense to add this information? Maybe in the main README.md?

**Comment by bms63** [comment]
I think it might be nice to have in both.   A short blurb in the general repo and then the same blurb in the workflows folder?  I'm thinking that folks won't thoroughly read the general repo read me, but once things break or get weird with the workflows seeing that readme in the workflow folder could be handy??

**Comment by cicdguy** [comment]
I can just link one to the other,  to keep it DRY
