### ISSUE TITLE
Feature Request:  Use package versions from `renv.lock` in workflows

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraltemplate#22]
### Feature Idea

I would propose that the workflows use the package versions from `renv.lock` instead of installing the latest one. Otherwise, it is hard to reproduce the findings of the workflow and it could happen that a workflow fails because a new version of a package like `styler` was released.

**Comment by bms63** [comment]
I agree we should be using the same from `admiral`.

**Comment by cicdguy** [comment]
When you say "workflow", @bundfussr, you mean the GHA CI workflows? If so, they already do this.

**Comment by bundfussr** [comment]
@dinakar29 , I am referring to `lintr.yaml`, `spellcheck.yml`(, and `style.yml`). They install the latest version of lintr, spelling, styler instead of using the one from renv.lock. `style.yml` is not yet in admiraltemplate but had the same problem in admiralonco. The versions of `style.yml` we have in admiral and admiralonco should be ok.
