### ISSUE TITLE
Feature Request:  Centralize Package Dependencies for Workflows

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraltemplate#23]
### Feature Idea

If possible, I would like to centralize the install dependencies step in the workflows which call functions from the extension package.
Usually it contains code like
```
          ref <- if (Sys.getenv("GITHUB_REF_NAME") == "main") "main" else "devel"
          remotes::install_github(
            "pharmaverse/admiral.test",
            ref = ref,
            dependencies = FALSE,
            upgrade = "never"
          )
```
for all admiral packages the extension package is depending on.

Maybe we could also have a simple file where the admiral dependencies are listed (and function which reads in the file in the install dependencies step). Something like
```
admiral.test: main
admiral: devel
admiralonco: devel
```
The value after the package indicates which version of the package should be used:
- `main`: Always use the `main` version of the package
- `devel`: Use the `devel` version of the package for PRs into `devel` and the `main` version for PRs into `main`.

**Comment by cicdguy** [comment]
Yes, this is possible with staged.dependencies: https://github.com/openpharma/staged.dependencies
We also have a Github action for this: https://github.com/marketplace/actions/staged-dependencies-action

**Comment by bundfussr** [comment]
@dinakar29 , are the downstream dependencies in `staged_dependencies.yml` required?

**Comment by cicdguy** [comment]
> @dinakar29 , are the downstream dependencies in `staged_dependencies.yml` required?

Not for admiral and its extensions, no.
