### ISSUE TITLE
Feature Request:  Simplify creating and maintaining `renv.lock`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiraltemplate#24]
### Feature Idea

Manually updating the `renv.lock` is tedious because it is not clear if an entry is required by admiral core or the extension package.

I would propose
- to add a `package.lock` file which contains only those packages which are required by the extension package but not by admiral core (or other admiral extension packages) and
- to implement a function in admiral or admiraldev which collates the packages from `package.lock` and the `renv.lock` files of all admiral packages the extension package is depending on and writes the `renv.lock` file.

Open question: Should the `renv.lock` contain other admiral packages?

**Comment by galachad** [comment]
I prefer to keep all dependencies in the lock file but in that case the `staged_dependencies` will not be used. 

I do not get this idea for having the multiple lock file. I understand the possibility for optimization  but in that case, we can try with profiles. 

For easy generating `renv.lock` file you probably would like to use `explicit` option.

The `explicit` option will collect the packages but omit Suggest one and it's correct behaviour. 

```
package.dependency.fields: Imports, Depends, LinkingTo
```

We should not add `Suggests` from all packages as we will be get version conflicts , we only want to get the `Suggests` packages from `admiraldev`.

Solutions:
1) Create custom field in `admiraldev` e.g. `SuggestsAdmiral` - not nice, duplicate record in `DESCRIPTION`
2) Use custom method for renv discovery
```
.get_dependencies <- function(project_dir) {
  admdev_loc <- find.package("admiraldev", lib.loc = .libPaths(), quiet = TRUE)
  adm_dev_suggests <- renv:::renv_dependencies_discover_description(admdev_loc, fields = "Suggests")

  names(renv:::renv_package_dependencies(c(project_dir, adm_dev_suggests[["Package"]])))
}

options(renv.snapshot.filter = .get_dependencies)
```

The snapshot type should be set to custom`snapshot.type: custom` in `renv/settings.dcf`.

Summary:
We can collect packages 
> "explicit" - Only capture packages which are explicitly listed in the project DESCRIPTION file.  [[1]](https://rstudio.github.io/renv/reference/snapshot.html#snapshot-type)

and add as extra packages Suggest packages from `admiraldev`.

The packages scope is a little bit bigger as now renv iterating  on packages from `DESCRIPTIONs` not doing `renv::dependency` discovery.  This method is also faster as `renv::dependency` iterating on files.

 
 @bundfussr please check if this solution fits your need. It's really simple to implement. Can be just part of `.Rprofile`.


The renv.lock can be simply snapshot just after `renv::install()`.

**Comment by bundfussr** [comment]
@galachad , thanks for the feedback. I think this issue is not up to date. Meanwhile we decided to use a single lock file for all admiral repositories.
The lock file should contain all packages which are imported or suggested by any of the admiral packages. The version of the packages should be the one which was  available when the R version we are using for development was released. At the moment we use R 4.0. I.e., we would store the version in the lock which was available when R 4.0 was released.
There should be an option to use newer versions for some packages. For example, we use a newer version of pkgdown.
The admiral packages should not be in the lock file because these are handled by staged_dependencies.

**Comment by bms63** [comment]
Can we close this issue?

**Comment by bundfussr** [comment]
@bms63 , yes, I think we should create an issue for the renv.lock generation in admiralci.

**Comment by bundfussr** [comment]
I have created https://github.com/pharmaverse/admiralci/issues/51 for further discussion.
