### ISSUE TITLE
Feature Request:  Use `cookiecutter` for faster extension boostrapping

### ISSUE THREAD

**Issue by cicdguy** [pharmaverse/admiraltemplate#25]
### Feature Idea

Given how many manual steps are involved in creating a new admiral extension, consider minimizing the number of manual steps and autonating extension boostrapping by restructuring this template with the 
[`cookiecutter` framework](https://cookiecutter.readthedocs.io/en/stable/).

### Relevant Input

Someone runs `cookiecutter gh:pharmaverse/admiraltemplate` and follows the prompts to initialize a new extension, instead of reading a document on the steps involved in initializing a new extension.

### Relevant Output

The extension package is fully bootstrapped via `cookiecutter`.

### Reproducible Example/Pseudo Code

Eg:

```bash
# Install cookiecutter
pip3 install cookiecutter

# Try it out on an example repo
cookiecutter gh:audreyr/cookiecutter-pypackage
```

**Comment by rossfarrugia** [comment]
@dinakar29 nice idea but i'd say a nice to have and not something to overly prioritise. i found the manual steps pretty easy to follow. lets close out all the other open admiral pieces for your team first.
