### ISSUE TITLE
@bms63 , we need the `docs` folder and the `pkgdown.yml` file to enable linking across different admiral packages. For example, if we have `admiral::derive_vars_merged()` in the admiralonco documentation, it will link to the admiral documentation.

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#35]
@bms63 , we need the `docs` folder and the `pkgdown.yml` file to enable linking across different admiral packages. For example, if we have `admiral::derive_vars_merged()` in the admiralonco documentation, it will link to the admiral documentation.

So please do not remove it.

_Originally posted by @bundfussr in https://github.com/pharmaverse/admiral/issues/1298#issuecomment-1188731853_

**Comment by rossfarrugia** [comment]
@bundfussr would you be ok to pick up this one? i wasn't quite sure of the update needed. do you think this one is essential before i make the {admiralvaccine} new repo? i'm trying to get that set up this week, but doing some admiraltemplate clean ups first

**Comment by bundfussr** [comment]
I think no update is needed. `pkgdown.yml` is a generated file. So there is no need to add it to admiraltemplate. In `.gitignore` the file is listed as an exception. It will be listed as modified in git if the documentation was updated.

Thus I'll close this issue.

**Comment by bms63** [comment]
I think I was saying that the way admiralonco is linking documentation from admiral using `pkgdown.yml` file should be set up in the template and documented.  So admiralvaccines could easily take advantage of this.

**Comment by bundfussr** [comment]
If you want to link from the admiralonco documentation to an admiral function, the important bit is that `docs/pkgdown.yml` exists in admiral and that the urls are defined in the `DESCRIPTION` and `_pkgdown.yml` file of admiral. As far as I remember no special setup on the admiralonco side is required.

However, to be able to link to admiralonco functions (for example from a company specific admiral extension) `pkgdown.yml` and urls should be provided in admiralonco as well. I think adiraltemplate takes this into account already.

**Comment by bms63** [comment]
Good to know.  I thought something had to be set up in admiralonco as well.
