### ISSUE TITLE
Step-by-step guide in Readme

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#4]
How does one use this template repo to get their package set up

**Comment by bms63** [comment]
Click Use this Template and name your package extension repo

  1. Download Repo to RStudio and run renv::restore() - you will see a prompt and this will take a few minutes
  2. Update DESCRIPTION file with your package name, authors, etc
  3. Run devtools::load_all() - debug
  4. Run devtools::check() - debug
  5. Run pkgdown::build_site()
  6. Go forth and deliver

**Comment by bms63** [comment]
Probably some info about what can be deleted

**Comment by rossfarrugia** [comment]
your latest version looks good to me, i added one extra:
Any clearly dummy files like R/my_first_fcn.R or inst/templates/ad_adxx.R can be updated or removed.

will close this and please re-open if more still to do.
