### ISSUE TITLE
General Issue: Review content and update as needed

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#48]
### Background Information

We developed this template repo a year and some of the content is outdated.  

A full review is needed and updates/discussion can either be made with the issue tagged or additional issues can be created.

### Definition of Done

- [ ] Thorough review of Files
- [ ] Update relevant files

**Comment by zdz2101** [comment]
@bms63 I can take a look into this one, can I get access to the repo?

**Comment by bms63** [comment]
omg yes please!!
