### ISSUE TITLE
Bug: New template "About" link breaks because of the way we set up CI/CD

### ISSUE THREAD

**Issue by zdz2101** [pharmaverse/admiraltemplate#52]
### What happened?

![image](https://user-images.githubusercontent.com/43018762/230439337-873d2473-12ea-4840-9a56-e7f04f860fb6.png)

### Reproducible Example

![image](https://user-images.githubusercontent.com/43018762/230439450-771e969c-e72c-4076-879f-e74500351344.png)

I suspect if we switch these from "cran-release" to "main" it should solve it, but because we are not sending this off to CRAN this breaks. Should we still modify for a package's first website they need to point to _not_ cran-release because it will not have been released to CRAN yet?

**Comment by zdz2101** [comment]
@bms63 @rossfarrugia Seems like I may have broken something, if you go to the github repo, and click the URL on the top right, you'll land at a 404 error. For the purpose of a 1st package developer, think we might need to have a more thoughtful discussion on how to set up these templates. 

Perhaps add a snippet in this template to watch out for this file specifically and the URL paths the developer may be interested at that moment in time?

**Comment by rossfarrugia** [comment]
@zdz2101 yes that's exactly the reason as https://pharmaverse.github.io/admiraltemplate/main/ still works fine so the package site has rendered OK. I agree that this needs to be updated as new packages would render a site to check in `main` first before making a CRAN release as you say. agree @bms63?

**Comment by bms63** [comment]
I think the package needs to be "released" for the website to build now.  

![image](https://user-images.githubusercontent.com/10111024/230458179-7e37a156-be0e-4f97-b033-fcd5ff3fe427.png)

![image](https://user-images.githubusercontent.com/10111024/230458097-7afdb847-1d9c-427d-83b5-914381e2a596.png)

**Comment by zdz2101** [comment]
Oh thats fascinating

**Comment by bms63** [comment]
Everything is working on website- but I think we forgot to update something in here - 
![image](https://user-images.githubusercontent.com/10111024/230463578-0125e67d-3afa-4669-8490-6c3ffb7ba521.png)

As the Get Started page is falling over.
