### ISSUE TITLE
Update README - Quick Start Guide for Template

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiraltemplate#59]
### Let us know where something needs a refresh or put your idea here!

Can we add `.Rbuildignore`/`.gitignore`/`.lycheeignore`/`_pkgdown.yml` to the following part of the README?

![image](https://github.com/pharmaverse/admiraltemplate/assets/47867131/f95d4ef8-b4be-46bc-8a5d-f809829529fd)

**Comment by bms63** [comment]
@pharmaverse/admiral This is a good first issue to keep our template repo up to date.

**Comment by rossfarrugia** [comment]
README looks to be reduced now and i cant find mention of this anymore so will close.
