### ISSUE TITLE
Update workflows to be generic and mimic current admiral setup

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraltemplate#7]
workflow fire once you copy over...need to fire only on PR

not up to date with current admiral setup

**Comment by bms63** [comment]
i got the workflows going for the different versions of $.  We can't use the identical package version snapshots from the admiral workflows as I would think this admiralextension package would want admiral as a package - this wasn't present in previous snapshots of CRAN until this year!!  

@dinakar29 can we do the 2020 snapshot with a call to 2022 admiral package?  Not sure if that is possible?

![image](https://user-images.githubusercontent.com/10111024/174881792-b0a307f1-3ec4-4339-9d23-96b3a65f55c2.png)

**Comment by cicdguy** [comment]
Hi @bms63 - let me take a look at this one in more detail. Likely that we'll need to add another repo under the `repos` list to get the desired version of admiral.
