### ISSUE TITLE
Documentation: Package extension guidance should link to admiraldev site

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiraltemplate#71]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

@bms63 @manciniedoardo should https://pharmaverse.github.io/admiraltemplate/cran-release/index.html#package-extension-guidance be replaced with a link to https://pharmaverse.github.io/admiraldev/articles/package_extensions.html now? i trust the admiraldev site version is the one we should refer to for admiralpeds

**Comment by manciniedoardo** [comment]
@rossfarrugia yes this is correct, the admiraldev one has been reviewed and is a more up-to-date of what is currently in the template repo.

**Comment by rossfarrugia** [comment]
@bms63 @manciniedoardo  I'll take on this issue and also update any other minor spots i can see for this template comparing against things we updated for admiralpeds
