### ISSUE TITLE
General Issue: Remove non-ASCII characters in the package

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiraltemplate#82]
### Background Information

Non-ASCII characters cause NOTES to appear when running pre-release checks. We should remove any from the package to avoid any issues. This is especially important in admiraltemplate, which is used as the basis of so many packages!

### Definition of Done

- Run the following in the searchbar on github:
 `repo:pharmaverse/admiraltemplate /[^\x00-\x7F]+/`
- Remove anything flagged.

**Comment by bms63** [comment]
Nice easy one to help us out! This is about to be used for admiralmetabolic!!  So we want to have in tip top shape!!

@pharmaverse/admiral @pharmaverse/admiral_comm
